### ISSUE TITLE
Possible New Feature: Read from files

### ISSUE THREAD

**Issue by kialio** [andrewramsay/ical_to_gcal_sync#17]
Hello,

I have an exchange calendar that I want to sync from my local machine to google calendar.  It's stored locally as a folder full of *.ics files.  I quickly wrote a new function that's a wrapper for get_current_events() called get_current_events_from_files() that loops through the ics files and returns the cal dictionary.  To use this, I added a global in config.py called 'FILES' which, when set to True assumes the ICAL_FEED global is a path and not a url.  There were a few other things I modified to get this to work.

Is this a feature that is desirable or is this a corner case that's only useful to me.  I'm happy to send a pull request.

Thanks for the code, making my life better...

J.

**Comment by andrewramsay** [comment]
I don't think it's something I'd ever end up using myself but no reason not to add it in if it's made optional through config.py, there might be other people out there who would appreciate it. Feel free to send the PR!

**Comment by kialio** [comment]
PR is #18

**Comment by andrewramsay** [comment]
Merged as #18
